INSERT INTO Type VALUES(NULL,"nature");
INSERT INTO Type VALUES(NULL,"aux fruits avec morceaux");
INSERT INTO Type VALUES(NULL,"mixés/brassés");
INSERT INTO Type VALUES(NULL,"aromatisés");
INSERT INTO Type VALUES(NULL,"bifidus nature");
INSERT INTO Type VALUES(NULL,"bifidus aux fruits");
INSERT INTO Type VALUES(NULL,"bio");
INSERT INTO Type VALUES(NULL,"anti-cholestrérol");
INSERT INTO Type VALUES(NULL,"allégés");
INSERT INTO Type VALUES(NULL,"à boire");
INSERT INTO Type VALUES(NULL,"0%");
