INSERT INTO Gout VALUES(NULL,"Fraise");
INSERT INTO Gout VALUES(NULL,"Banane");
INSERT INTO Gout VALUES(NULL,"Framboise");
INSERT INTO Gout VALUES(NULL,"Cassis");
INSERT INTO Gout VALUES(NULL,"Coing");
INSERT INTO Gout VALUES(NULL,"Pêche");
INSERT INTO Gout VALUES(NULL,"Abricot");
INSERT INTO Gout VALUES(NULL,"Ananas");
