INSERT INTO Type VALUES(NULL,"Fraise");
INSERT INTO Type VALUES(NULL,"Banane");
INSERT INTO Type VALUES(NULL,"Framboise");
INSERT INTO Type VALUES(NULL,"Cassis");
INSERT INTO Type VALUES(NULL,"Coing");
INSERT INTO Type VALUES(NULL,"Pêche");
INSERT INTO Type VALUES(NULL,"Abricot");
INSERT INTO Type VALUES(NULL,"Ananas");
